"""Cross-reference the SysEx-only sweep against typebar_full to identify
which TYPE bytes correspond to which effects, and what knob addresses
each effect uses.

Outputs a per-TYPE table: TYPE byte, effect name (from typebar_full if
known), default param values, knob count.
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

FXITEM0_BASE = 0x10001100


def decode_4nibble(payload: bytes) -> int:
    """4-nibble offset binary → display value. payload must be 4 bytes."""
    if len(payload) != 4:
        return None
    raw = ((payload[0] & 0x0F) << 12) | ((payload[1] & 0x0F) << 8) | \
          ((payload[2] & 0x0F) << 4) | (payload[3] & 0x0F)
    return raw - 0x8000


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl", default="captures/bts_full_sweep/sweep.jsonl")
    ap.add_argument("--typebar", default="captures/typebar_full")
    ap.add_argument("--out-md", default="captures/bts_full_sweep/per_type_table.md")
    ap.add_argument("--out-json", default="captures/bts_full_sweep/per_type.json")
    args = ap.parse_args()

    # Load sweep results
    blocks: dict[int, bytes] = {}
    actual_for: dict[int, int] = {}  # what the device actually stored
    for line in Path(args.jsonl).read_text().splitlines():
        try:
            rec = json.loads(line)
        except Exception:
            continue
        if "type" not in rec or rec.get("block") is None:
            continue
        blocks[rec["type"]] = bytes.fromhex(rec["block"])
        actual_for[rec["type"]] = rec.get("actual", rec["type"])
    print(f"loaded {len(blocks)} TYPEs from sweep")

    # Load typebar_full
    typebar_by_type_byte: dict[int, dict] = {}
    typebar_dir = Path(args.typebar)
    if typebar_dir.exists():
        for f in sorted(typebar_dir.glob("page*/*/summary.json")):
            try:
                d = json.loads(f.read_text())
            except Exception:
                continue
            triplet = d.get("triplet_at_10001100", "")
            if len(triplet) >= 2:
                tb = int(triplet[:2], 16)
                typebar_by_type_byte[tb] = d
    print(f"typebar_full reference: {len(typebar_by_type_byte)} TYPE bytes mapped")

    # Per-TYPE breakdown
    rows = []
    for t in sorted(blocks):
        block = blocks[t]
        actual = actual_for.get(t, t)
        tbf = typebar_by_type_byte.get(actual)
        # Knobs per typebar_full
        knobs = (tbf or {}).get("knobs", []) if tbf else []
        knob_addrs = [k.get("address") for k in knobs]
        # Decode defaults at each FX-Param slot (Param 1..32 reachable via segment 0)
        params = []
        for n in range(1, 33):
            offset = 0x03 + (n - 1) * 4
            if offset + 4 > len(block):
                break
            payload = block[offset:offset + 4]
            disp = decode_4nibble(payload)
            params.append({"n": n, "offset": offset, "addr": f"0x{(FXITEM0_BASE + offset):08X}",
                           "default_hex": payload.hex(), "default_disp": disp})

        # Identify "live" knobs in this effect: from typebar_full mapping
        # Knob name from typebar_full per address
        knob_name_by_addr = {}
        for k in knobs:
            addr = k.get("address")
            name = k.get("name_manual_v2") or k.get("name_manual")
            if addr:
                knob_name_by_addr[addr] = name

        rows.append({
            "type_byte": f"0x{t:02X}",
            "type_byte_int": t,
            "actual_stored": f"0x{actual:02X}",
            "is_clamped": (actual != t),
            "effect_name": (tbf or {}).get("name") if tbf else None,
            "n_typebar_knobs": len(knobs),
            "knob_addresses": knob_addrs,
            "knob_names_by_addr": knob_name_by_addr,
            "default_params_full": params,
        })

    # Write JSON
    Path(args.out_json).write_text(json.dumps(rows, indent=2))
    print(f"wrote {args.out_json}")

    # Write Markdown summary
    md = []
    md.append("# GX-10 effect TYPE table — programmatic SysEx sweep")
    md.append("")
    md.append(f"Generated by `tools/sweep_all_types.py` + `tools/analyze_sweep_v2.py` "
              f"on {Path(args.jsonl).name}.")
    md.append("")
    md.append(f"- TYPEs probed: {len(blocks)}")
    md.append(f"- Effects in typebar_full: {len(typebar_by_type_byte)}")
    md.append("")
    md.append("## Findings")
    md.append("")
    md.append("- **Device clamps TYPE byte at 0x52.** Writes of 0x53..0x7F all stored as 0x52. "
              "Valid effect TYPE range is **0x00..0x52** (83 effects).")
    # Effects we found but typebar_full missed
    missing_in_typebar = [r for r in rows
                          if 0 <= r["type_byte_int"] <= 0x52
                          and r["effect_name"] is None
                          and not r["is_clamped"]]
    if missing_in_typebar:
        md.append(f"- **TYPEs in valid range but missing from typebar_full:** "
                  + ", ".join(r["type_byte"] for r in missing_in_typebar)
                  + ".")
    md.append("")
    md.append("## Per-TYPE table")
    md.append("")
    md.append("| TYPE | Effect | typebar knobs | Knob addresses |")
    md.append("|------|--------|--------------:|----------------|")
    for r in rows:
        if r["is_clamped"]:
            continue
        if r["type_byte_int"] > 0x52:
            continue
        name = r["effect_name"] or "**(missing)**"
        addrs = r["knob_addresses"]
        addr_str = ", ".join(addrs[:6]) + ("…" if len(addrs) > 6 else "")
        md.append(f"| `{r['type_byte']}` | {name} | {r['n_typebar_knobs']} | {addr_str} |")
    md.append("")
    md.append("## TYPEs that clamped")
    md.append("")
    md.append("| Written TYPE | Stored as |")
    md.append("|--------------|-----------|")
    for r in rows:
        if r["is_clamped"]:
            md.append(f"| `{r['type_byte']}` | `{r['actual_stored']}` |")
    md.append("")
    md.append("## Knob-address structure")
    md.append("")
    md.append("Every effect uses the same 4-byte slot pattern at offset stride 0x04:")
    md.append("- offset +0x00..+0x02 = FX TYPE / ON-OFF / DupNum (header)")
    md.append("- offset +0x03 = FX Param 1 (often a sub-type or mode)")
    md.append("- offset +0x07 = FX Param 2 (first knob, knob_idx 0)")
    md.append("- offset +0x0B = FX Param 3 (knob_idx 1)")
    md.append("- offset +0x0F = FX Param 4 (knob_idx 2)")
    md.append("- ... offset +0x03 + (N-1)*4 = FX Param N")
    md.append("")
    md.append("Each FX Param is 4 bytes, 4-nibble offset binary "
              "(`display = (raw - 0x8000)`).")
    md.append("")
    md.append("Address byte 4 must be ≤ 0x7F (Roland 7-bit-per-byte rule), so "
              "FX Param 1..32 are reachable in segment 0 (offsets 0x03..0x7F). "
              "Effects in this catalog use ≤21 params (max observed offset = 0x53), "
              "so the segment-2 region (offsets 0x80..0xFF, addressed via "
              "0x10001200..0x1000127F) appears unused.")

    Path(args.out_md).write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {args.out_md}")


if __name__ == "__main__":
    main()
