"""Aggregate every effect's summary.json into one Markdown reference doc."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
TYPEBAR = ROOT / "captures" / "typebar_full"
OUT_MD = ROOT / "docs" / "effects" / "all_effects.md"
OUT_JSON = ROOT / "docs" / "effects" / "all_effects.json"


def main():
    rows = []
    for page_dir in sorted(TYPEBAR.glob("page*")):
        for eff_dir in sorted(page_dir.iterdir()):
            sp = eff_dir / "summary.json"
            if not sp.exists():
                continue
            try:
                rows.append(json.loads(sp.read_text()))
            except Exception:
                pass
    rows.sort(key=lambda r: (r.get("page", 99), r.get("idx", 99)))

    # Write JSON
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(rows, indent=2, default=list))

    # Build Markdown
    md = ["# GX-10 — Complete Effect & Knob Map", "",
          "Auto-generated by `tools/build_effects_doc.py` from per-effect",
          "drag captures, TYPE/SP TYPE popup cycling, batched knob sweeps,",
          "and HARMONY-knob/SP_TYPE-driven layout exploration.",
          "",
          "## Master table",
          "",
          "| Page | Idx | Effect | Type @0x10001100 | TYPE# | SP TYPE# | Base | +TYPE | +SP | +HRM | Total |",
          "|-----:|----:|--------|:----------------:|:-----:|:--------:|-----:|------:|----:|-----:|------:|"]
    for r in rows:
        ttype = r.get("triplet_at_10001100", "-")
        ttype = ttype[:2] if ttype else "-"
        type_n = (r.get("type_max", -1) + 1) if r.get("has_type") else "-"
        sp_n = (r.get("sp_type_max", -1) + 1) if r.get("has_sp_type") else "-"
        base = len(r.get("knobs", []))
        extras = r.get("knobs_extra", [])
        n_type_extra = sum(1 for e in extras if "first_seen_at_type" in e)
        n_sp_extra = sum(1 for e in extras if "first_seen_at_sp_type" in e)
        n_harm_extra = sum(1 for e in extras
                            if "first_seen_at_harmony_step" in e
                            or e.get("first_seen_at") == "2:HARMONY=USER")
        total = base + len(extras)
        md.append(f"| {r['page']} | {r['idx']:2d} | **{r['name']}** | "
                  f"`0x{ttype}` | {type_n} | {sp_n} | {base} | "
                  f"{n_type_extra or '-'} | {n_sp_extra or '-'} | "
                  f"{n_harm_extra or '-'} | {total} |")

    md.append("\n## Per-effect detail\n")
    for r in rows:
        md.append(f"### {r['name']}  (page {r['page']}, idx {r['idx']})")
        md.append("")
        md.append(f"- Color RGB: {r.get('color')}")
        ttype = r.get("triplet_at_10001100", "-")
        md.append(f"- Effect type byte at 0x10001100: `0x{ttype[:2]}`")
        md.append(f"- Hex x position (window-local): {r.get('hex_x')}")
        md.append(f"- Drag pcap: `captures/typebar_full/page{r['page']}/{r['idx']:02d}_{r['name']}/drag.pcap`")
        if r.get("has_type"):
            md.append(f"- TYPE address: `{r.get('type_address')}`, "
                      f"{(r.get('type_max', -1) + 1)} entries")
        if r.get("has_sp_type"):
            md.append(f"- SP TYPE address: `{r.get('sp_type_address')}`, "
                      f"{(r.get('sp_type_max', -1) + 1)} entries")
        knobs = r.get("knobs", [])
        if knobs:
            md.append("")
            md.append("**Base knobs** (default TYPE=0 layout):")
            md.append("")
            md.append("| # | Name | x,y | Address | min | max |")
            md.append("|--:|:-----|:----|:--------|----:|----:|")
            for k in knobs:
                nm = k.get('name_manual', '?')
                # Prefer 4-nibble-decoded display values
                vmin = k.get('min_display', k.get('min'))
                vmax = k.get('max_display', k.get('max'))
                md.append(f"| {k.get('knob_idx')} | {nm} | "
                          f"{k.get('knob_x')},{k.get('knob_y')} | "
                          f"`{k.get('address') or '-'}` | "
                          f"{vmin} | {vmax} |")
        extras = r.get("knobs_extra", [])
        if extras:
            md.append("")
            md.append("**Additional knobs** (revealed at non-default TYPE / SP TYPE / HARMONY):")
            md.append("")
            md.append("| Name | x,y | Address | min | max | seen-at |")
            md.append("|:-----|:----|:--------|----:|----:|:--------|")
            for k in extras:
                seen = k.get("first_seen_at_type") and f"TYPE={k['first_seen_at_type']}"
                if not seen:
                    seen = k.get("first_seen_at_sp_type") and f"SP_TYPE={k['first_seen_at_sp_type']}"
                if not seen:
                    seen = k.get("first_seen_at_harmony_step") and f"HARM={k['first_seen_at_harmony_step']}"
                if not seen:
                    seen = k.get("first_seen_at") or "-"
                nm = k.get('name_manual', '?')
                vmin = k.get('min_display', k.get('min'))
                vmax = k.get('max_display', k.get('max'))
                md.append(f"| {nm} | {k.get('knob_x')},{k.get('knob_y')} | "
                          f"`{k.get('address') or '-'}` | "
                          f"{vmin} | {vmax} | {seen} |")

        # TYPE / SP_TYPE / HARMONY layout group summaries
        tg = r.get("per_type_layouts")
        if tg:
            md.append("")
            md.append("**Per-TYPE knob layouts** (knob master indices visible per TYPE):")
            md.append("")
            for entry in tg:
                md.append(f"- TYPE={entry['type_value']}: "
                          f"{len(entry['knob_master_indices'])} knobs "
                          f"({entry['knob_master_indices']})")
        spg = r.get("sp_type_layout_groups")
        if spg:
            md.append("")
            md.append("**SP_TYPE layout groups**:")
            md.append("")
            for g in spg:
                sv = g["sp_type_values"]
                preview = f"{sv[:5]}{'...' if len(sv) > 5 else ''}"
                md.append(f"- {g['n_knobs']} knobs at SP_TYPE values "
                          f"{preview} ({len(sv)} entries)")
        hg = r.get("harmony_layout_groups")
        if hg:
            md.append("")
            md.append("**HARMONY-driven layout groups**:")
            md.append("")
            for g in hg:
                steps = g["harmony_steps"]
                preview = f"{steps[:5]}{'...' if len(steps) > 5 else ''}"
                md.append(f"- {g['n_knobs']} knobs at HARMONY steps "
                          f"{preview} ({len(steps)} entries)")
        dpd = r.get("delay_plus_dual_dropdowns")
        if dpd:
            md.append("")
            md.append("**DUAL extra dropdowns** (TYPE=5):")
            md.append("")
            md.append("| Dropdown | Values | Address |")
            md.append("|----------|-------:|---------|")
            for name, info in dpd.items():
                md.append(f"| {name.replace('_', '.')} | "
                          f"{info['n_values']} | `{info['address']}` |")
        md.append("")
        md.append("Min/Max display values: see `captures/typebar_full/"
                  f"page{r['page']}/{r['idx']:02d}_{r['name']}/knobs_min.png` "
                  "and `knobs_max.png`.")
        md.append("")
        md.append("---")
        md.append("")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(md), encoding="utf-8")
    print(f"wrote {OUT_MD} ({len(rows)} effects)")
    print(f"wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
