"""Official 83-entry MemoryFxItem TYPE enum (byte → effect name).

Source: GX-100/GX-10 MIDI Implementation chart, MemoryFxItem section.

This module is the Python-import face of the same table also published as
`catalogs/fx_type_enum.json` for cross-language consumers. Both are
hand-maintained from the MIDI chart; keep them in sync when adding entries.

Usage:
    from fx_type_enum import FX_TYPE_NAME
    print(FX_TYPE_NAME[0x02])  # → "AIRD PREAMP"
"""
FX_TYPE_NAME = {
    0:  "AC GUITAR SIMULATOR",
    1:  "AC RESONANCE",
    2:  "AIRD PREAMP",
    3:  "AIRD BASS PREAMP",
    4:  "CHORUS",
    5:  "BASS CHORUS",
    6:  "PRIME CHORUS",
    7:  "CLASSIC-VIBE",
    8:  "COMPRESSOR",
    9:  "X-COMP",
    10: "X-BASS COMP",
    11: "DEFRETTER",
    12: "BASS DEFRETTER",
    13: "DELAY",
    14: "DELAY PLUS",
    15: "ANALOG DELAY",
    16: "SPACE ECHO",
    17: "SHIMMER DELAY",
    18: "TWIST",
    19: "WARP",
    20: "PARAMETRIC EQUALIZER",
    21: "GRAPHIC EQUALIZER",
    22: "FLANGER",
    23: "BASS FLANGER",
    24: "FLANGER PRIME",
    25: "BASS FLANGER PRIME",
    26: "HARMONIST",
    27: "BASS HARMONIST",
    28: "PHRASE LOOP",
    29: "DIVIDER",
    30: "SPLITTER",
    31: "MIXER",
    32: "NOISE SUPPRESSOR",
    33: "OCTAVE",
    34: "OCTAVE POLY",
    35: "OCTAVE BASS",
    36: "BOOSTER",
    37: "OVERDRIVE",
    38: "BASS OVERDRIVE",
    39: "DISTORTION",
    40: "BASS DISTORTION",
    41: "FUZZ",
    42: "BASS FUZZ",
    43: "X-OD",
    44: "X-BASS OD",
    45: "X-DS",
    46: "METAL",
    47: "BASS METAL",
    48: "OVERTONE",
    49: "PAN",
    50: "FOOT VOLUME",
    51: "PEDAL BEND",
    52: "BASS PEDAL BEND",
    53: "WAH",
    54: "BASS_WAH",
    55: "PHASER",
    56: "BASS PHASER",
    57: "PRIME PHASER",
    58: "PRIME BASS PHASER",
    59: "SCRIPT PHASER",
    60: "PITCH SHIFTER",
    61: "BASS PITCH SHIFTER",
    62: "REVERB",
    63: "REVERB PLUS",
    64: "SHIMMER REVERB",
    65: "TERA ECHO",
    66: "RING MODULATOR",
    67: "ROTARY",
    68: "S-BEND",
    69: "BASS S-BEND",
    70: "SLOW GEAR",
    71: "BASS SLOW GEAR",
    72: "TOUCH WAH",
    73: "BASS TOUCH WAH",
    74: "TREMOLO",
    75: "VIBRATO",
    76: "VIBRATO PRIME",
    77: "SEND/RETURN",
    78: "SLICER",
    79: "HUMANIZER",
    80: "FEEDBACKER",
    81: "SITAR SIM",
    82: "AUTO WAH",
}
assert len(FX_TYPE_NAME) == 83
